define([], function () {"use strict";var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}}};
	sjcl.cipher.aes=function(a){this.b[0][0][0]||this.h();var b,c,d,e,f=this.b[0][4],g=this.b[1];b=a.length;var h=1;if(4!==b&&6!==b&&8!==b)throw new sjcl.exception.invalid("invalid aes key size");this.f=[d=a.slice(0),e=[]];for(a=b;a<4*b+28;a++){c=d[a-1];if(0===a%b||8===b&&4===a%b)c=f[c>>>24]<<24^f[c>>16&255]<<16^f[c>>8&255]<<8^f[c&255],0===a%b&&(c=c<<8^c>>>24^h<<24,h=h<<1^283*(h>>7));d[a]=d[a-b]^c}for(b=0;a;b++,a--)c=d[b&3?a:a-4],e[b]=4>=a||4>b?c:g[0][f[c>>>24]]^g[1][f[c>>16&255]]^g[2][f[c>>8&255]]^g[3][f[c&
	255]]};
	sjcl.cipher.aes.prototype={encrypt:function(a){return v(this,a,0)},decrypt:function(a){return v(this,a,1)},b:[[[],[],[],[],[]],[[],[],[],[],[]]],h:function(){var a=this.b[0],b=this.b[1],c=a[4],d=b[4],e,f,g,h=[],l=[],m,n,k,p;for(e=0;0x100>e;e++)l[(h[e]=e<<1^283*(e>>7))^e]=e;for(f=g=0;!c[f];f^=m||1,g=l[g]||1){k=g^g<<1^g<<2^g<<3^g<<4;k=k>>8^k&255^99;c[f]=k;d[k]=f;n=h[e=h[m=h[f]]];p=0x1010101*n^0x10001*e^0x101*m^0x1010100*f;n=0x101*h[k]^0x1010100*k;for(e=0;4>e;e++)a[e][f]=n=n<<24^n>>>8,b[e][k]=p=p<<24^p>>>8}for(e=
																																																																																																																																																																																																																																																																		 0;5>e;e++)a[e]=a[e].slice(0),b[e]=b[e].slice(0)}};
	function v(a,b,c){if(4!==b.length)throw new sjcl.exception.invalid("invalid aes block size");var d=a.f[c],e=b[0]^d[0],f=b[c?3:1]^d[1],g=b[2]^d[2];b=b[c?1:3]^d[3];var h,l,m,n=d.length/4-2,k,p=4,q=[0,0,0,0];h=a.b[c];a=h[0];var r=h[1],s=h[2],t=h[3],u=h[4];for(k=0;k<n;k++)h=a[e>>>24]^r[f>>16&255]^s[g>>8&255]^t[b&255]^d[p],l=a[f>>>24]^r[g>>16&255]^s[b>>8&255]^t[e&255]^d[p+1],m=a[g>>>24]^r[b>>16&255]^s[e>>8&255]^t[f&255]^d[p+2],b=a[b>>>24]^r[e>>16&255]^s[f>>8&255]^t[g&255]^d[p+3],p+=4,e=h,f=l,g=m;for(k=
																																																																																																																																																																																																																																																												0;4>k;k++)q[c?3&-k:k]=u[e>>>24]<<24^u[f>>16&255]<<16^u[g>>8&255]<<8^u[b&255]^d[p++],h=e,e=f,f=g,g=b,b=h;return q}
	sjcl.bitArray={bitSlice:function(a,b,c){a=sjcl.bitArray.m(a.slice(b/32),32-(b&31)).slice(1);return void 0===c?a:sjcl.bitArray.clamp(a,c-b)},extract:function(a,b,c){var d=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-d^a[b/32+1|0]>>>d:a[b/32|0]>>>d)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],d=sjcl.bitArray.getPartial(c);return 32===d?a.concat(b):sjcl.bitArray.m(b,d,c|0,a.slice(0,a.length-1))},bitLength:function(a){var b=a.length;return 0===
		b?0:32*(b-1)+sjcl.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b&=31;0<c&&b&&(a[c-1]=sjcl.bitArray.partial(b,a[c-1]&2147483648>>b-1,1));return a},partial:function(a,b,c){return 32===a?b:(c?b|0:b<<32-a)+0x10000000000*a},getPartial:function(a){return Math.round(a/0x10000000000)||32},equal:function(a,b){if(sjcl.bitArray.bitLength(a)!==sjcl.bitArray.bitLength(b))return!1;var c=0,d;for(d=0;d<a.length;d++)c|=a[d]^b[d];return 0===
			c},m:function(a,b,c,d){var e;e=0;for(void 0===d&&(d=[]);32<=b;b-=32)d.push(c),c=0;if(0===b)return d.concat(a);for(e=0;e<a.length;e++)d.push(c|a[e]>>>b),c=a[e]<<32-b;e=a.length?a[a.length-1]:0;a=sjcl.bitArray.getPartial(e);d.push(sjcl.bitArray.partial(b+a&31,32<b+a?c:d.pop(),1));return d},o:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]},byteswapM:function(a){var b,c;for(b=0;b<a.length;++b)c=a[b],a[b]=c>>>24|c>>>8&0xff00|(c&0xff00)<<8|c<<24;return a}};
	sjcl.codec.utf8String={fromBits:function(a){var b="",c=sjcl.bitArray.bitLength(a),d,e;for(d=0;d<c/8;d++)0===(d&3)&&(e=a[d/4]),b+=String.fromCharCode(e>>>8>>>8>>>8),e<<=8;return decodeURIComponent(escape(b))},toBits:function(a){a=unescape(encodeURIComponent(a));var b=[],c,d=0;for(c=0;c<a.length;c++)d=d<<8|a.charCodeAt(c),3===(c&3)&&(b.push(d),d=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),d));return b}};
	sjcl.codec.hex={fromBits:function(a){var b="",c;for(c=0;c<a.length;c++)b+=((a[c]|0)+0xf00000000000).toString(16).substr(4);return b.substr(0,sjcl.bitArray.bitLength(a)/4)},toBits:function(a){var b,c=[],d;a=a.replace(/\s|0x/g,"");d=a.length;a+="00000000";for(b=0;b<a.length;b+=8)c.push(parseInt(a.substr(b,8),16)^0);return sjcl.bitArray.clamp(c,4*d)}};
	sjcl.codec.base32={e:"ABCDEFGHIJKLMNOPQRSTUVWXYZ234567",k:"0123456789ABCDEFGHIJKLMNOPQRSTUV",BITS:32,BASE:5,REMAINING:27,fromBits:function(a,b,c){var d=sjcl.codec.base32.BASE,e=sjcl.codec.base32.REMAINING,f="",g=0,h=sjcl.codec.base32.e,l=0,m=sjcl.bitArray.bitLength(a);c&&(h=sjcl.codec.base32.k);for(c=0;f.length*d<m;)f+=h.charAt((l^a[c]>>>g)>>>e),g<d?(l=a[c]<<d-g,g+=e,c++):(l<<=d,g-=d);for(;f.length&7&&!b;)f+="=";return f},toBits:function(a,b){a=a.replace(/\s|=/g,"").toUpperCase();var c=sjcl.codec.base32.BITS,
			d=sjcl.codec.base32.BASE,e=sjcl.codec.base32.REMAINING,f=[],g,h=0,l=sjcl.codec.base32.e,m=0,n,k="base32";b&&(l=sjcl.codec.base32.k,k="base32hex");for(g=0;g<a.length;g++){n=l.indexOf(a.charAt(g));if(0>n){if(!b)try{return sjcl.codec.base32hex.toBits(a)}catch(p){}throw new sjcl.exception.invalid("this isn't "+k+"!");}h>e?(h-=e,f.push(m^n>>>h),m=n<<c-h):(h+=d,m^=n<<c-h)}h&56&&f.push(sjcl.bitArray.partial(h&56,m,1));return f}};
	sjcl.codec.base32hex={fromBits:function(a,b){return sjcl.codec.base32.fromBits(a,b,1)},toBits:function(a){return sjcl.codec.base32.toBits(a,1)}};
	sjcl.codec.base64={e:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(a,b,c){var d="",e=0,f=sjcl.codec.base64.e,g=0,h=sjcl.bitArray.bitLength(a);c&&(f=f.substr(0,62)+"-_");for(c=0;6*d.length<h;)d+=f.charAt((g^a[c]>>>e)>>>26),6>e?(g=a[c]<<6-e,e+=26,c++):(g<<=6,e-=6);for(;d.length&3&&!b;)d+="=";return d},toBits:function(a,b){a=a.replace(/\s|=/g,"");var c=[],d,e=0,f=sjcl.codec.base64.e,g=0,h;b&&(f=f.substr(0,62)+"-_");for(d=0;d<a.length;d++){h=f.indexOf(a.charAt(d));
			if(0>h)throw new sjcl.exception.invalid("this isn't base64!");26<e?(e-=26,c.push(g^h>>>e),g=h<<32-e):(e+=6,g^=h<<32-e)}e&56&&c.push(sjcl.bitArray.partial(e&56,g,1));return c}};sjcl.codec.base64url={fromBits:function(a){return sjcl.codec.base64.fromBits(a,1,1)},toBits:function(a){return sjcl.codec.base64.toBits(a,1)}};sjcl.hash.sha256=function(a){this.f[0]||this.h();a?(this.g=a.g.slice(0),this.d=a.d.slice(0),this.a=a.a):this.reset()};sjcl.hash.sha256.hash=function(a){return(new sjcl.hash.sha256).update(a).finalize()};
	sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.g=this.l.slice(0);this.d=[];this.a=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.d=sjcl.bitArray.concat(this.d,a);b=this.a;a=this.a=b+sjcl.bitArray.bitLength(a);if(0x1fffffffffffff<a)throw new sjcl.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var d=new Uint32Array(c),e=0;for(b=512+b-(512+b&0x1ff);b<=a;b+=512)w(this,d.subarray(16*e,
			16*(e+1))),e+=1;c.splice(0,16*e)}else for(b=512+b-(512+b&0x1ff);b<=a;b+=512)w(this,c.splice(0,16));return this},finalize:function(){var a,b=this.d,c=this.g,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this.a/0x100000000));for(b.push(this.a|0);b.length;)w(this,b.splice(0,16));this.reset();return c},l:[],f:[],h:function(){function a(a){return 0x100000000*(a-Math.floor(a))|0}for(var b=0,c=2,d,e;64>b;c++){e=!0;for(d=2;d*d<=c;d++)if(0===c%d){e=
			!1;break}e&&(8>b&&(this.l[b]=a(Math.pow(c,0.5))),this.f[b]=a(Math.pow(c,1/3)),b++)}}};
	function w(a,b){var c,d,e,f=a.g,g=a.f,h=f[0],l=f[1],m=f[2],n=f[3],k=f[4],p=f[5],q=f[6],r=f[7];for(c=0;64>c;c++)16>c?d=b[c]:(d=b[c+1&15],e=b[c+14&15],d=b[c&15]=(d>>>7^d>>>18^d>>>3^d<<25^d<<14)+(e>>>17^e>>>19^e>>>10^e<<15^e<<13)+b[c&15]+b[c+9&15]|0),d=d+r+(k>>>6^k>>>11^k>>>25^k<<26^k<<21^k<<7)+(q^k&(p^q))+g[c],r=q,q=p,p=k,k=n+d|0,n=m,m=l,l=h,h=d+(l&m^n&(l^m))+(l>>>2^l>>>13^l>>>22^l<<30^l<<19^l<<10)|0;f[0]=f[0]+h|0;f[1]=f[1]+l|0;f[2]=f[2]+m|0;f[3]=f[3]+n|0;f[4]=f[4]+k|0;f[5]=f[5]+p|0;f[6]=f[6]+q|0;f[7]=
		f[7]+r|0}sjcl.misc.hmac=function(a,b){this.j=b=b||sjcl.hash.sha256;var c=[[],[]],d,e=b.prototype.blockSize/32;this.c=[new b,new b];a.length>e&&(a=b.hash(a));for(d=0;d<e;d++)c[0][d]=a[d]^909522486,c[1][d]=a[d]^1549556828;this.c[0].update(c[0]);this.c[1].update(c[1]);this.i=new b(this.c[0])};sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(a){if(this.n)throw new sjcl.exception.invalid("encrypt on already updated hmac called!");this.update(a);return this.digest(a)};
	sjcl.misc.hmac.prototype.reset=function(){this.i=new this.j(this.c[0]);this.n=!1};sjcl.misc.hmac.prototype.update=function(a){this.n=!0;this.i.update(a)};sjcl.misc.hmac.prototype.digest=function(){var a=this.i.finalize(),a=(new this.j(this.c[1])).update(a).finalize();this.reset();return a};
	sjcl.misc.pbkdf2=function(a,b,c,d,e){c=c||1E4;if(0>d||0>c)throw new sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));e=e||sjcl.misc.hmac;a=new e(a);var f,g,h,l,m=[],n=sjcl.bitArray;for(l=1;32*m.length<(d||1);l++){e=f=a.encrypt(n.concat(b,[l]));for(g=1;g<c;g++){f=a.encrypt(f);for(h=0;h<f.length;h++)e[h]^=f[h]}m=m.concat(e)}d&&(m=n.clamp(m,d));return m};
	sjcl.misc.hkdf=function(a,b,c,d,e){var f,g=[];e=e||sjcl.hash.sha256;"string"===typeof d&&(d=sjcl.codec.utf8String.toBits(d));"string"===typeof c?c=sjcl.codec.utf8String.toBits(c):c||(c=[]);c=new sjcl.misc.hmac(c,e);c=c.mac(a);a=sjcl.bitArray.bitLength(c);a=Math.ceil(b/a);if(255<a)throw new sjcl.exception.invalid("key bit length is too large for hkdf");c=new sjcl.misc.hmac(c,e);f=[];for(e=1;e<=a;e++)c.update(f),c.update(d),c.update([sjcl.bitArray.partial(8,e)]),f=c.digest(),g=sjcl.bitArray.concat(g,
		f);return sjcl.bitArray.clamp(g,b)};"undefined"!==typeof module&&module.exports&&(module.exports=sjcl);"function"===typeof define&&define([],function(){return sjcl});
	return sjcl; });
